spring.application.name=gestion-practicas

# 1. Dirección de la base de datos (JDBC)
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.wwbsitavfnayjsmvclxu
spring.datasource.password=@tfgpwd2026

# 2. Driver y Dialecto (Para que Java hable "PostgreSQL 17")
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. Magia de Hibernate: 'update' crea las tablas en Supabase automáticamente según tus clases Java
spring.jpa.hibernate.ddl-auto=update

# 4. Ver lo que pasa por debajo (Logs)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true