spring.application.name=gestion-practicas

# Puerto
server.port=${PORT:8081}

# Base de datos Supabase PostgreSQL - Para el despliegue. 
# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}

# Base de datos Supabase - Para local. 

# Base de datos Supabase - Para local con Session Pooler
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres.wwbsitavfnayjsmvclxu}
spring.datasource.password=${DB_PASSWORD:@fpconnectA123}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Logs SQL
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Supabase Storage - Para despliegue. 
# supabase.url=${SUPABASE_URL}
# supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY}
# supabase.storage.bucket=cv

# Supabase Storage - Local. 
supabase.url=${SUPABASE_URL:https://wwbsitavfnayjsmvclxu.supabase.co}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3YnNpdGF2Zm5heWpzbXZjbHh1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Mjg3Mjk3MywiZXhwIjoyMDg4NDQ4OTczfQ.C4eSoW8hJSTYBCmXfkxKQsQYqRtCMaT8yHPED8sdnHs}
supabase.storage.bucket=${SUPABASE_STORAGE_BUCKET:cv}

# Tamaño máximo de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB