spring.application.name=gestion-practicas

# 1. Configuración de Conexión (SOLO UNA)
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.wwbsitavfnayjsmvclxu
spring.datasource.password=@tfgpwd2026

# 2. Driver y Dialecto (Forzamos el dialecto para que no dé el error que te acaba de salir)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Estrategia de Tablas
spring.jpa.hibernate.ddl-auto=update

# 4. Logs para ver que funciona
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 5. Por si no funciona localhost:8080
server.port=8081